# Generated by Django 3.2 on 2021-05-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزییات سبد خرید', 'verbose_name_plural': 'اطلاعات جزییات سبدهای خرید'},
        ),
    ]
