# Generated by Django 3.2 on 2021-04-29 09:21

import Gil_Products_Category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products_Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Gil_Products_Category.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
