# Generated by Django 3.1.7 on 2021-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='آدرس محصول'),
            preserve_default=False,
        ),
    ]
