# Generated by Django 3.2 on 2021-04-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products_Category', '0002_auto_20210429_1351'),
        ('Gil_Products', '0004_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gil_Products_Category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
