# Generated by Django 3.1.7 on 2021-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی\u200cپی')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='موجود / ناموجود'),
        ),
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Gil_Products.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
