# Generated by Django 3.1.7 on 2021-07-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products_Category', '0001_initial'),
        ('Gil_Products', '0005_auto_20210630_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Gil_Products_Category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
