# Generated by Django 3.2 on 2021-05-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Product_Brand', '0001_initial'),
        ('Gil_Products', '0006_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gil_Product_Brand.productbrand', verbose_name='برندها'),
        ),
    ]
