# Generated by Django 3.1.7 on 2021-07-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Product_Brand', '0001_initial'),
        ('Gil_Products', '0006_auto_20210704_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Gil_Product_Brand.productbrand', verbose_name='برندها'),
        ),
    ]
