# Generated by Django 3.1.7 on 2021-07-15 16:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products', '0007_auto_20210706_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات محصول'),
        ),
    ]
