# Generated by Django 3.2 on 2021-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products', '0011_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.TextField(null=True, verbose_name='ویژگی های محصول'),
        ),
    ]
