# Generated by Django 3.1.7 on 2021-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_account', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='کاربر فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='سوپر ادمین'),
        ),
    ]
