# Generated by Django 3.2 on 2021-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_account', '0005_auto_20210426_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
