# Generated by Django 3.2 on 2021-05-01 16:59

import Gil_Product_Brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gil_Products_Category', '0002_auto_20210429_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام برند')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان در URL')),
                ('description', models.TextField(verbose_name='توضیحات برند')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Gil_Product_Brand.models.upload_image_path, verbose_name='تصویر')),
                ('categories', models.ManyToManyField(blank=True, to='Gil_Products_Category.ProductCategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
    ]
