# Generated by Django 3.2 on 2021-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Sliders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('link', models.URLField(blank=True, max_length=150, null=True, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='<function upload_image_path at 0x0000021D9D130CA0>/advertise', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'پست تبلیغی',
                'verbose_name_plural': 'پست های تبلیغی',
            },
        ),
    ]
