# Generated by Django 3.2 on 2021-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Sliders', '0002_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<function upload_image_path at 0x0000023246F70CA0>/advertise', verbose_name='تصویر'),
        ),
    ]
