# Generated by Django 3.2 on 2021-05-12 17:36

import Gil_Sliders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Sliders', '0003_alter_advertise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Gil_Sliders.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
