# Generated by Django 3.2 on 2021-05-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Products', '0009_auto_20210505_1243'),
        ('Gil_Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Gil_Products.product', verbose_name='نام محصول'),
        ),
    ]
