# Generated by Django 3.2 on 2021-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gil_Comment', '0003_comments_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False, verbose_name='نمایش / عدم نمایش'),
        ),
    ]
